project:
  type: website
  output-dir: docs

website:
  title: "Influenza (sub)clade nomenclature"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: none
    minimal: true
    css: styles.css
    toc: false